wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 5
      - 8
      4: 3.8.6
      5: 0.10.23
      8:
      - 1
      - 5
